create database capstone;
 
 create table capstone.brands (Brand_id int primary key,Brand_name varchar(100));
 
 create table capstone.categories (Category_id int primary key, category_name varchar(100));
 
 create table capstone.customers (customer_id int primary key,First_name varchar(100),Last_name varchar(100),
 Phone varchar(100),Email varchar(100),street varchar(100),city varchar(100),state varchar(100),zip_code int);
 
 create table capstone.order_items (order_id int,item_id int,product_id int,quantity int,list_price double,
 discount double,total_price double);
 
 create table capstone.orders (order_id int Primary key,customer_id int,order_status text,order_date text,
 required_date text,shipped_date text,store_id int,staff_id int);
 
 create table capstone.products (Product_id int Primary key,Product_name varchar(100),Brand_id int,Category_id int,
Model_year int,List_price double);

 create table capstone.staffs (Staff_id int Primary key,first_name varchar(100),last_name varchar(100),Email varchar(100),
phone varchar(100),Active int,Store_id int,manager_id varchar(100));

 create table capstone.stocks (Store_id int,Product_id int,Quantity int);
 
 create table capstone.stores (Store_id int primary key,store_name varchar(100),phone varchar(100),Email varchar(100),
street varchar(100),City varchar(100),state varchar(100),Zip_code int);
 
 
 
 
-- Inner Join for Order Details 
-- Join orders, order_items, and products to display detailed line items. 
select * from capstone.orders as o
inner join capstone.order_items as od
on o.order_id = od.order_id
inner join capstone.products as p
on p.Product_id = od.Product_id;



-- Total Sales by Store 
-- Write a query to group sales (total_price) by each store_id.
select sum(od.Total_price) as Total_sales,s.store_id from capstone.order_items as od
join capstone.orders as o
on o.order_id = od.order_id
join capstone.stores as s
on o.store_id = s.store_id 
group by s.Store_id;

-- Top 5 Selling Products
-- Use ORDER BY and LIMIT to get the top 5 most sold products by quantity.
 select sum(oi.quantity) as QUANTITy,p.product_name
 from capstone.order_items as oi
 inner join capstone.products as p
 on oi.Product_id = p.Product_id
 group by p.Product_name
 order by QUANTITY desc limit 5;
 
 --  Customer Purchase Summary 
 -- For each customer, return total orders placed, total items purchased, and total revenue. 
 select o.Customer_id,count(oi.order_id) as Total_orders,sum(oi.Total_price) as Total_revenue,sum(oi.quantity) as Total_item_purchased
 from capstone.orders as o
 join capstone.order_items as oi
 on oi.order_id = o.order_id
 group by o.customer_id
 order by Total_orders,Total_revenue;
 
 
 -- Segment Customers by Total Spend
 -- Write a query to classify customers into spending brackets (e.g., low, medium, high). 
 select o.customer_id,sum(oi.Total_price) as Total_spending,
 case
 when sum(oi.Total_price) < 10000 then "Low"
 when sum(oi.Total_price) between 10000 and 15000 then "Medium"
 else "High"
end as spending_segment
from capstone.orders as o
join capstone.order_items as oi
on o.order_id = oi.order_id
group by o.customer_id;

-- Staff Performance Analysis
-- Analyze total revenue generated by each staff member based on their handled orders. 
select s.staff_id,round(sum(oi.total_price),2) as Total_revenue
from capstone.orders as o
join capstone.staffs as s
on s.Staff_id = o.staff_id
join capstone.order_items as oi
on oi.order_id = o.order_id
group by s.Staff_id;

--  Stock Alert Query 
--  Write a query to list products where stock quantity < 10 in any store.
 select str.store_id,p.product_id,p.Product_name,s.quantity
 from capstone.stores as str
 join capstone.stocks as s
 on s.Store_id = str.Store_id
 join capstone.products as p
 on p.Product_id = s.Product_id
 where s.quantity < 10;
 
 create table capstone.customer_segments(customer_id varchar(50),recency int,frequency int,monetary decimal(12,2));
 select * from capstone.customer_segments;
 
alter table capstone.customer_segments
add column segment varchar(30);
SET SQL_SAFE_UPDATES=0;

UPDATE capstone.customer_segments
SET Segment =
CASE
WHEN Recency <= 180 AND Frequency >= 2 AND Monetary >= 5000
THEN 'Loyal'
WHEN Recency <= 365 AND Frequency >= 1
THEN 'New'
ELSE 'At Risk'
END;

